# https://taskfile.dev

---
version: '3'

vars:
  RACE_FLAG: ''

tasks:
  changelog:
    desc: Show the list of changes since the last tag
    cmds:
      - git log $(git describe --tags --abbrev=0)..HEAD --oneline

  ## utility commands

  bumpy-exists:
    internal: true
    cmds:
      - which bumpy
    silent: true
